[members]
workspace = [
   "rust/algorithms",
]

[package]
name = "bst"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"

[[bin]]
name = "avl"
path = "src/avl.rs"

[[bin]]
name = "bst"
path = "src/bst.rs"

[[bin]]
name = "avl_tree_set"
path = "src/avl_tree_set.rs"